version: '3'

services:
  drupal:
    image: drupal:8.5.3-apache
    ports:
      - '9090:80' 
    # volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  pgsql:
    image: postgres:10.3
    environment:
      POSTGRES_PASSWORD: cay.12123
